package forms.validation;

import classes.admin;
import classes.auth;
import classes.pegawai;
import classes.session;
import db.connection.connection;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {

    public Connection conn;
    JFrame frame = new JFrame();

    public login() {
        initComponents();
        connection connect = new connection();
        this.conn = connect.koneksi();
        setExtendedState(frame.MAXIMIZED_BOTH);
        resetform();
    }

    public void resetform() {
        txtusername.setText(null);
        txtpassword.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        cardlay = new javax.swing.JPanel();
        form = new javax.swing.JPanel();
        password = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        line1 = new javax.swing.JLabel();
        line2 = new javax.swing.JLabel();
        button = new javax.swing.JLabel();
        card = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));

        bg.setBackground(new java.awt.Color(187, 187, 187));
        bg.setMaximumSize(new java.awt.Dimension(1920, 1080));
        bg.setMinimumSize(new java.awt.Dimension(720, 480));

        cardlay.setBackground(new java.awt.Color(187, 187, 187));
        cardlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setFont(new java.awt.Font("Bree Serif", 0, 15)); // NOI18N
        password.setForeground(new java.awt.Color(91, 90, 90));
        password.setText("password");
        form.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 187, -1, -1));

        login.setFont(new java.awt.Font("Bree Serif", 1, 30)); // NOI18N
        login.setText("Login");
        form.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 6, -1, -1));

        username.setFont(new java.awt.Font("Bree Serif", 0, 15)); // NOI18N
        username.setForeground(new java.awt.Color(91, 90, 90));
        username.setText("username");
        form.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 92, -1, -1));

        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(68, 68, 68));
        txtusername.setBorder(null);
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        form.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 126, 365, 30));

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(68, 68, 68));
        txtpassword.setBorder(null);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        form.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 221, 365, 30));

        line1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/login/line.png"))); // NOI18N
        form.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 156, -1, -1));

        line2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/login/line.png"))); // NOI18N
        form.add(line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 251, -1, -1));

        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/login/button.png"))); // NOI18N
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        form.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 370, -1, -1));

        cardlay.add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 490, 460));

        card.setBackground(new java.awt.Color(187, 187, 187));
        card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/login/card.png"))); // NOI18N
        cardlay.add(card, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(cardlay, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(cardlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
        String Username = txtusername.getText().toString();
        String Password = txtpassword.getText().toString();
        auth auth = new auth();
        pegawai pgw = new pegawai();

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {

                pegawai validate_pegawai = auth.pegawai(Username, Password);
                
                if (Username.isEmpty() || Password.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Username atau Password tidak boleh kosong!");
                    resetform();
                } else if (validate_pegawai.getId_pegawai() != 0) {

                    String privileges = validate_pegawai.getPrivileges().toString();
                    if (validate_pegawai.getPrivileges().equals("Admin")) {
                        this.setVisible(false);
                        new forms.admin.index().setVisible(true);
                    } else if (validate_pegawai.getPrivileges().equals("Manager")) {
                        this.setVisible(false);
                        new forms.pegawai.manager.index().setVisible(true);
                    } else if (validate_pegawai.getPrivileges().equals("Kasir")) {
                        this.setVisible(false);
                        new forms.pegawai.kasir.index().setVisible(true);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Username atau Password yang anda masukan salah!");
                    resetform();
                }

            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_txtpasswordKeyPressed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
         String Username = txtusername.getText().toString();
        String Password = txtpassword.getText().toString();
        auth auth = new auth();
        pegawai pgw = new pegawai();

            try {

                pegawai validate_pegawai = auth.pegawai(Username, Password);
                
                if (Username.isEmpty() || Password.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Username atau Password tidak boleh kosong!");
                    resetform();
                } else if (validate_pegawai.getId_pegawai() != 0) {

                    String privileges = validate_pegawai.getPrivileges().toString();
                    if (validate_pegawai.getPrivileges().equals("Admin")) {
                        this.setVisible(false);
                        new forms.admin.index().setVisible(true);
                    } else if (validate_pegawai.getPrivileges().equals("Manager")) {
                        this.setVisible(false);
                        new forms.pegawai.manager.index().setVisible(true);
                    } else if (validate_pegawai.getPrivileges().equals("Kasir")) {
                        this.setVisible(false);
                        new forms.pegawai.kasir.index().setVisible(true);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Username atau Password yang anda masukan salah!");
                    resetform();
                }

            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        
    }//GEN-LAST:event_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel button;
    private javax.swing.JLabel card;
    private javax.swing.JPanel cardlay;
    private javax.swing.JPanel form;
    private javax.swing.JLabel line1;
    private javax.swing.JLabel line2;
    private javax.swing.JLabel login;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
