package forms.admin;

import classes.admin;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class account extends javax.swing.JFrame {

    public Connection conn;

    public account() {
        initComponents();
        this.setResizable(false);
        resetform();
    }

    public void resetform() {
        txtusername.setText(null);
        txtpassword.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        layuser = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        txtuser = new javax.swing.JLabel();
        layform = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        laypass = new javax.swing.JPanel();
        txtpassword = new javax.swing.JTextField();
        layform1 = new javax.swing.JLabel();
        txtpass = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(790, 446));
        setMinimumSize(new java.awt.Dimension(790, 446));
        setPreferredSize(new java.awt.Dimension(790, 446));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        layuser.setBackground(new java.awt.Color(255, 255, 255));
        layuser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtusername.setBorder(null);
        txtusername.setSelectionColor(new java.awt.Color(190, 91, 32));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        layuser.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 250, 24));

        txtuser.setFont(new java.awt.Font("Bree Serif", 0, 18)); // NOI18N
        txtuser.setText("username");
        layuser.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        layform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/layform.png"))); // NOI18N
        layform.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        layuser.add(layform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/b.simpan.png"))); // NOI18N
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });

        laypass.setBackground(new java.awt.Color(255, 255, 255));
        laypass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtpassword.setBorder(null);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        laypass.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 250, 24));

        layform1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/layform.png"))); // NOI18N
        layform1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        laypass.add(layform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        txtpass.setFont(new java.awt.Font("Bree Serif", 0, 18)); // NOI18N
        txtpass.setText("password");
        laypass.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/b.cancel.png"))); // NOI18N
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(simpan)
                        .addGap(18, 18, 18)
                        .addComponent(cancel))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(layuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(laypass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laypass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(layuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(simpan)
                    .addComponent(cancel))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Mengubah Data Tersebut?");
        String username = txtusername.getText().toString();
        String password = txtpassword.getText().toString();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Salah Satu Data Kosong, Mohon Isi Semua Data Dengan Benar");
        } else {
            admin adm = new admin();

            adm.setUsername(username);
            adm.setPassword(password);

            boolean editted = adm.edit_data(adm);

            if (editted) {
                JOptionPane.showMessageDialog(this, "Berhasil Edit Data!", "Success Insert", JOptionPane.INFORMATION_MESSAGE);
                resetform();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal Edit Data, Coba Ulangi Kembali!", "Failed Insert", JOptionPane.ERROR_MESSAGE);
            }
        }

        resetform();
    }//GEN-LAST:event_simpanMouseClicked

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        this.setVisible(false);
        new forms.admin.index().setVisible(true);
    }//GEN-LAST:event_cancelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel layform;
    private javax.swing.JLabel layform1;
    private javax.swing.JPanel laypass;
    private javax.swing.JPanel layuser;
    private javax.swing.JLabel simpan;
    private javax.swing.JLabel txtpass;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JLabel txtuser;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
