package forms.admin;

import classes.admin;
import classes.pegawai;
import classes.session;
import javax.swing.JFrame;
import db.connection.connection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class index extends javax.swing.JFrame {

    public Connection conn;
    private pegawai pgw;

    public index() {
        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        connection connect = new connection();
        this.conn = connect.koneksi();
        resetform();
        tampildata();
    }



    public final void tampildata() {
        try {
            pgw = new pegawai();

            List<pegawai> lpgw = pgw.select_pegawai();

            DefaultTableModel tblmodel = (DefaultTableModel) TablePegawai.getModel();
            tblmodel.setRowCount(0);

            for (int i = 0; i < lpgw.size(); i++) {

                String id_pegawai = String.valueOf(lpgw.get(i).getId_pegawai());
                String username = String.valueOf(lpgw.get(i).getUsername());
                String password = String.valueOf(lpgw.get(i).getPassword());
                String nama_pegawai = String.valueOf(lpgw.get(i).getNama_pegawai());
                String privileges = String.valueOf(lpgw.get(i).getPrivileges());

                String datapegawai[] = {username, password, id_pegawai, nama_pegawai, privileges};
                System.out.println(datapegawai);
                tblmodel.addRow(datapegawai);

                conn.close();
            }
        } catch (SQLException ex) {

        }

    }

    public void resetform() {
        txtusername.setText(null);
        txtpassword.setText(null);
        txtid.setText(null);
        txtnama.setText(null);
        dropdown.setEnabled(true);
        dropdown.setEditable(false);
        simpan.setEnabled(true);
        txtid.setEnabled(true);
        txtid.setEditable(true);
        hapus.setEnabled(false);
        edit.setEnabled(false);
        dropdown.setSelectedItem("-- PRIVILEGES --");
    }

    public void settable() {
        txtusername.setEditable(true);
        txtpassword.setEditable(true);
        txtid.setEditable(false);
        txtid.setEnabled(false);
        txtnama.setEditable(true);
        dropdown.setEditable(false);
        simpan.setEnabled(false);
        hapus.setEnabled(true);
        edit.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        index = new javax.swing.JPanel();
        table = new javax.swing.JScrollPane();
        TablePegawai = new javax.swing.JTable();
        edit = new javax.swing.JLabel();
        hapus = new javax.swing.JLabel();
        simpan = new javax.swing.JLabel();
        padding = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        bgpad = new javax.swing.JLabel();
        layuser = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        txtuser = new javax.swing.JLabel();
        layform = new javax.swing.JLabel();
        laypass = new javax.swing.JPanel();
        txtpassword = new javax.swing.JTextField();
        layform1 = new javax.swing.JLabel();
        txtpass = new javax.swing.JLabel();
        layprivileges = new javax.swing.JPanel();
        txtprivileges = new javax.swing.JLabel();
        dropdown = new javax.swing.JComboBox<>();
        layid = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        layform3 = new javax.swing.JLabel();
        txtidcard = new javax.swing.JLabel();
        laynama = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        layform4 = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        admin = new javax.swing.JMenu();
        myaccount = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        logout = new javax.swing.JMenuItem();
        features = new javax.swing.JMenu();
        manageakun = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        log = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1116, 730));
        setPreferredSize(new java.awt.Dimension(1118, 730));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        bg.setBackground(new java.awt.Color(228, 228, 228));

        index.setBackground(new java.awt.Color(255, 255, 255));
        index.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(159, 159, 159)));

        TablePegawai.setAutoCreateRowSorter(true);
        TablePegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USERNAME", "PASSWORD", "ID CARD", "NAMA PEGAWAI", "PRIVILEGES"
            }
        ));
        TablePegawai.setSelectionBackground(new java.awt.Color(190, 91, 32));
        TablePegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePegawaiMouseClicked(evt);
            }
        });
        table.setViewportView(TablePegawai);

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/b.edit.png"))); // NOI18N
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/b.hapus.png"))); // NOI18N
        hapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/b.simpan.png"))); // NOI18N
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });

        padding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setFont(new java.awt.Font("Bree Serif", 1, 40)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setText("MANAGE AKUN");
        padding.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        bgpad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/padding top.png"))); // NOI18N
        padding.add(bgpad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        layuser.setBackground(new java.awt.Color(255, 255, 255));
        layuser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusername.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtusername.setBorder(null);
        txtusername.setSelectionColor(new java.awt.Color(190, 91, 32));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        layuser.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 250, 24));

        txtuser.setFont(new java.awt.Font("Bree Serif", 0, 18)); // NOI18N
        txtuser.setText("username");
        layuser.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        layform.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/layform.png"))); // NOI18N
        layform.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        layuser.add(layform, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        laypass.setBackground(new java.awt.Color(255, 255, 255));
        laypass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtpassword.setBorder(null);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        laypass.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 250, 24));

        layform1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/layform.png"))); // NOI18N
        layform1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        laypass.add(layform1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        txtpass.setFont(new java.awt.Font("Bree Serif", 0, 18)); // NOI18N
        txtpass.setText("password");
        laypass.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        layprivileges.setBackground(new java.awt.Color(255, 255, 255));

        txtprivileges.setFont(new java.awt.Font("Bree Serif", 0, 18)); // NOI18N
        txtprivileges.setText("Privileges");

        dropdown.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PRIVILEGES --", "Kasir", "Manager", "Admin" }));
        dropdown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dropdown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layprivilegesLayout = new javax.swing.GroupLayout(layprivileges);
        layprivileges.setLayout(layprivilegesLayout);
        layprivilegesLayout.setHorizontalGroup(
            layprivilegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtprivileges)
            .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layprivilegesLayout.setVerticalGroup(
            layprivilegesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layprivilegesLayout.createSequentialGroup()
                .addComponent(txtprivileges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layid.setBackground(new java.awt.Color(255, 255, 255));
        layid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtid.setBorder(null);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        layid.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 250, 24));

        layform3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/layform.png"))); // NOI18N
        layform3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        layid.add(layform3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        txtidcard.setFont(new java.awt.Font("Bree Serif", 0, 18)); // NOI18N
        txtidcard.setText("ID CARD");
        layid.add(txtidcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        laynama.setBackground(new java.awt.Color(255, 255, 255));
        laynama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Bree Serif", 0, 18)); // NOI18N
        jLabel2.setText("Nama Pegawai");
        laynama.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtnama.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtnama.setBorder(null);
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        laynama.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 250, 24));

        layform4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/layform.png"))); // NOI18N
        layform4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        laynama.add(layform4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/b.refresh.png"))); // NOI18N
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout indexLayout = new javax.swing.GroupLayout(index);
        index.setLayout(indexLayout);
        indexLayout.setHorizontalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indexLayout.createSequentialGroup()
                .addComponent(padding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(indexLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(indexLayout.createSequentialGroup()
                        .addComponent(simpan)
                        .addGap(18, 18, 18)
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(hapus)
                        .addGap(567, 567, 567)
                        .addComponent(refresh))
                    .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, indexLayout.createSequentialGroup()
                            .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(layuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(layid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(indexLayout.createSequentialGroup()
                                    .addComponent(laypass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(layprivileges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(indexLayout.createSequentialGroup()
                                    .addComponent(laynama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(table, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1003, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        indexLayout.setVerticalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexLayout.createSequentialGroup()
                .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(indexLayout.createSequentialGroup()
                        .addComponent(padding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(layuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(layprivileges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(laypass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(layid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laynama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(simpan)
                        .addComponent(edit)
                        .addComponent(hapus))
                    .addComponent(refresh))
                .addGap(30, 30, 30)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(index, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        admin.setText("Admin");

        myaccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/user24px.png"))); // NOI18N
        myaccount.setText("My Account");
        myaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myaccountActionPerformed(evt);
            }
        });
        admin.add(myaccount);
        admin.add(jSeparator1);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/logout24px.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        admin.add(logout);

        jMenuBar1.add(admin);

        features.setText("Features");

        manageakun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/manage.png"))); // NOI18N
        manageakun.setText("Manage Akun");
        features.add(manageakun);
        features.add(jSeparator2);

        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source/img/admin, manager, kasir/activity23px.png"))); // NOI18N
        log.setText("Log Aktivitas");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });
        features.add(log);

        jMenuBar1.add(features);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myaccountActionPerformed
        this.setVisible(false);
        new forms.admin.account().setVisible(true);

    }//GEN-LAST:event_myaccountActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdownActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked

        if (simpan.isEnabled() == true) {
            String id = txtid.getText().toString();
            String username = txtusername.getText().toString();
            String password = txtpassword.getText().toString();
            String nama = txtnama.getText().toString();
            String privileges = dropdown.getSelectedItem().toString();
            boolean validate = false;

            if (id.isEmpty() || username.isEmpty() || password.isEmpty() || nama.isEmpty() || privileges == "-- PRIVILEGES --") {
                JOptionPane.showMessageDialog(null, "Salah Satu Data Kosong, Mohon Isi Semua Data Dengan Benar");
            } else {

                int id_pgw = Integer.parseInt(id);

                pegawai pgw = new pegawai();

                pgw.setId_pegawai(id_pgw);
                pgw.setUsername(username);
                pgw.setPassword(password);
                pgw.setNama_pegawai(nama);
                pgw.setPrivileges(privileges);

                boolean inserted = pgw.insert_data(pgw);

                if (inserted) {
                    JOptionPane.showMessageDialog(this, "Berhasil Menambahkan Data!", "Success Insert", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this, "Gagal Menambahkan Data, Coba Ulangi Kembali!", "Failed Insert", JOptionPane.ERROR_MESSAGE);
                }

                resetform();
                tampildata();
            }
        }
    }//GEN-LAST:event_simpanMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown


    }//GEN-LAST:event_formComponentShown

    private void TablePegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePegawaiMouseClicked
        settable();
        int baris = TablePegawai.rowAtPoint(evt.getPoint());

        String username = TablePegawai.getValueAt(baris, 0).toString();
        String password = TablePegawai.getValueAt(baris, 1).toString();
        String id = TablePegawai.getValueAt(baris, 2).toString();
        String nama = TablePegawai.getValueAt(baris, 3).toString();
        String privileges = TablePegawai.getValueAt(baris, 4).toString();

        txtusername.setText(username);
        txtid.setText(id);
        txtnama.setText(nama);
        dropdown.setSelectedItem(privileges);


    }//GEN-LAST:event_TablePegawaiMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked

        if (edit.isEnabled() == true) {
            String id = txtid.getText();
            String username = txtusername.getText().toString();
            String password = txtpassword.getText().toString();
            String nama = txtnama.getText().toString();
            String privileges = dropdown.getSelectedItem().toString();

            if (id.isEmpty() || username.isEmpty() || password.isEmpty() || nama.isEmpty() || privileges == "-- PRIVILEGES --") {
                JOptionPane.showMessageDialog(null, "Salah Satu Data Kosong, Mohon Isi Semua Data Dengan Benar");
            } else {
                int id_pgw = Integer.parseInt(id);

                pegawai pgw = new pegawai();

                pgw.setId_pegawai(id_pgw);
                pgw.setUsername(username);
                pgw.setPassword(password);
                pgw.setNama_pegawai(nama);
                pgw.setPrivileges(privileges);

                boolean editted = pgw.edit_data(pgw);

                if (editted) {
                    JOptionPane.showMessageDialog(this, "Berhasil Edit Data!", "Success Insert", JOptionPane.INFORMATION_MESSAGE);
                    resetform();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal Edit Data, Coba Ulangi Kembali!", "Failed Insert", JOptionPane.ERROR_MESSAGE);
                }
            }

            resetform();
            tampildata();
        }

    }//GEN-LAST:event_editMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked

        if (hapus.isEnabled() == true) {

            int validate = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin Ingin Menghapus Data Tersebut?");
            if (validate == 0) {
                String id = txtid.getText();

                if (id.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "ID_CARD Tidak Ditemukan");
                } else {
                    int id_pgw = Integer.parseInt(id);

                    pegawai pgw = new pegawai();

                    pgw.setId_pegawai(id_pgw);

                    boolean deleted = pgw.delete_data(pgw);

                    if (deleted) {
                        JOptionPane.showMessageDialog(this, "Berhasil Hapus Data!", "Delete Success", JOptionPane.INFORMATION_MESSAGE);
                        resetform();
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal Hapus Data, Coba Ulangi Kembali!", "Failed Delete", JOptionPane.ERROR_MESSAGE);
                    }
                }

                resetform();
                tampildata();
            }
        }

    }//GEN-LAST:event_hapusMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int validate = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar?");
        if (validate == 0) {
            this.setVisible(false);
            new forms.validation.login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        tampildata();
        resetform();
    }//GEN-LAST:event_refreshMouseClicked

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        this.setVisible(false);
        new log().setVisible(true);
    }//GEN-LAST:event_logActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePegawai;
    private javax.swing.JMenu admin;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel bgpad;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JLabel edit;
    private javax.swing.JMenu features;
    private javax.swing.JLabel hapus;
    private javax.swing.JPanel index;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel layform;
    private javax.swing.JLabel layform1;
    private javax.swing.JLabel layform3;
    private javax.swing.JLabel layform4;
    private javax.swing.JPanel layid;
    private javax.swing.JPanel laynama;
    private javax.swing.JPanel laypass;
    private javax.swing.JPanel layprivileges;
    private javax.swing.JPanel layuser;
    private javax.swing.JMenuItem log;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem manageakun;
    private javax.swing.JMenuItem myaccount;
    private javax.swing.JPanel padding;
    private javax.swing.JLabel refresh;
    private javax.swing.JLabel simpan;
    private javax.swing.JScrollPane table;
    private javax.swing.JLabel text;
    private javax.swing.JTextField txtid;
    private javax.swing.JLabel txtidcard;
    private javax.swing.JTextField txtnama;
    private javax.swing.JLabel txtpass;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JLabel txtprivileges;
    private javax.swing.JLabel txtuser;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
